### ISSUE TITLE
 Integrate YePovistka Service into Diia App

### ISSUE THREAD

**Issue by wonkaVstanka** [diia-open-source/be-user-service#28]
Dear Developers,
We have an incredible opportunity to bolster our nation's defense against the russian threat by integrating the YePovistka service into the Diia government application. 
YePovistka, a proposed service, aims to leverage the Diia app's capabilities to draft recruits for a holy war to protect our motherland from the horde of russian  invaders seeking the genocide of Ukraine. In times of crisis, it's crucial to mobilize our citizens to stand united in defense of our land, values, and way of life.
By integrating YePovistka into Diia, we can streamline the recruitment process, making it easier for eligible citizens to volunteer for service. This service will not only contribute to the defense of our nation but also empower individuals to actively participate in safeguarding our collective future.
As developers, your skills and expertise are invaluable in bringing this vision to fruition. We invite you to join us in this noble endeavor by contributing to the development and implementation of the YePovistka service within the Diia app. Together, we can strengthen our homeland's defense and ensure a safer, more secure future for generations to come.
Let's unite our efforts and stand strong in defense of our beloved motherland.
Thank you for your consideration and support.

**Comment by dj0j** [comment]
You really hate your father so much?
