### ISSUE TITLE
Add the ability to reserve parking spaces in Dnipro

### ISSUE THREAD

**Issue by Ivanytskyi** [diia-open-source/be-user-service#39]
This is a very pressing problem in many cities, and especially in Dnipro. The ability to reserve and pay for parking spaces in Diya is a very good idea, because then a miracle can happen and the money from the parking lots will be used for their normal development, but this is not certain

**Comment by DiiaOpenSource** [comment]
Thank you for sharing current issues. We will pay attention to this; perhaps when we have the resources, we will try to do something
