### ISSUE TITLE
Use cryptographically-secure random number generator

### ISSUE THREAD

**Issue by AndriiDubonos** [diia-open-source/be-user-service#63]
Current implementation for OTP generation use `Math.random()` for random number generation. 
It's pseudo-random and should not be used as a number generator in security environment.

https://github.com/diia-open-source/be-user-service/blob/b45a0e2db354df110a99254516a414aaac43be61/src/services/otp.ts#L31

**Comment by yaroslav73** [comment]
But _cryptographically-secure_ is... pseudo-random also 🙃

**Comment by nyckyta** [comment]
I believe the point here is that it is possible to predict values from crypto insecure generator by observing previously generated values long enough. In other words, when intruder is able to observe sequence of generated values (even expired one), then he can derive the state of generator from them and thus to start to generate its own values that will be correct.

This issue does not appear when you use cryptographically safe algo as [doc](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) states.

**Comment by alinkedd** [comment]
Related to https://github.com/diia-open-source/be-auth-service/issues/1

**Comment by includesec-erik** [comment]
FYI @AndriiDubonos this issue would be closed if this PR is accepted:
https://github.com/diia-open-source/be-user-service/pull/99

**Comment by DiiaOpenSource** [comment]
Hi @AndriiDubonos 
Thank you for your attention. This is a duplicate issue: https://github.com/diia-open-source/be-auth-service/issues/1. Let's close this issue as a duplicate. Follow up on updates on issues that were opened earlier.
